framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        # Les 4 langues obligatoires du projet (§2).
        providers: ~
    enabled_locales: ['fr', 'pl', 'it', 'es']
